apiVersion: v1
kind: Secret
metadata:
  name: cluster-optimizer-aws
  namespace: cluster-optimizer
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: replace-me
  AWS_SECRET_ACCESS_KEY: replace-me
  AWS_REGION: us-east-1
