package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type rewriteContext map[string]string

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "rewrite-instructions-generator: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	var output string
	var clusterID string
	var namespace string
	var workload string
	var contextJSON string
	flags := flag.NewFlagSet("rewrite-instructions-generator", flag.ContinueOnError)
	flags.StringVar(&output, "output", "", "instructions.md output path")
	flags.StringVar(&clusterID, "cluster-id", "default", "cluster id")
	flags.StringVar(&namespace, "namespace", "", "Kubernetes namespace")
	flags.StringVar(&workload, "workload", "", "workload in Kind/name form")
	flags.StringVar(&contextJSON, "context-json", "{}", "recommendation context JSON")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if output == "" || namespace == "" || workload == "" {
		return errors.New("--output, --namespace, and --workload are required")
	}
	var ctx rewriteContext
	if err := json.Unmarshal([]byte(contextJSON), &ctx); err != nil {
		return fmt.Errorf("parse context JSON: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		return err
	}
	return os.WriteFile(output, []byte(renderInstructions(clusterID, namespace, workload, ctx)), 0o644)
}

func renderInstructions(clusterID, namespace, workload string, ctx rewriteContext) string {
	title := strings.ReplaceAll(workload, "/", " ")
	var b strings.Builder
	fmt.Fprintf(&b, "# Runtime Modernization Instructions: %s\n\n", title)
	fmt.Fprintf(&b, "Generated by Cluster Optimizer on %s.\n\n", time.Now().UTC().Format(time.RFC3339))

	b.WriteString("## Mission\n\n")
	b.WriteString("Implement a runtime modernization for this service only if measurement proves the current implementation cannot meet the target resource envelope with smaller, reversible changes. Prefer a focused Go implementation for memory-heavy always-on paths when it can preserve product behavior, reduce steady-state memory, and simplify operations. Do not rewrite broad product surface area without profiling evidence and an explicit migration plan.\n\n")

	b.WriteString("## Observed Recommendation\n\n")
	writeKV(&b, "Cluster", clusterID)
	writeKV(&b, "Namespace", namespace)
	writeKV(&b, "Workload", workload)
	writeKV(&b, "Rule", ctx.value("rule_id"))
	writeKV(&b, "Severity", ctx.value("severity"))
	writeKV(&b, "Evidence", ctx.value("evidence"))
	writeKV(&b, "Recommendation", ctx.value("recommendation"))
	writeKV(&b, "Expected cost effect", ctx.value("expected_cost_effect"))
	writeKV(&b, "Risk", ctx.value("risk"))
	writeKV(&b, "Confidence", ctx.value("confidence"))
	writeKV(&b, "Observed days", ctx.value("observed_days"))
	writeKV(&b, "Report occurrences", ctx.value("occurrences"))
	writeKV(&b, "First seen", ctx.value("first_seen_at"))
	writeKV(&b, "Last seen", ctx.value("last_seen_at"))

	b.WriteString("\n## Required Discovery\n\n")
	b.WriteString("- Read the existing repository before editing code. Identify the service entrypoint, public API, health endpoints, background workers, persistence layer, queues, third-party clients, auth model, config/env vars, and deployment manifests.\n")
	b.WriteString("- Establish the user-critical flows this service owns. Preserve request/response contracts, status codes, headers, error shapes, idempotency behavior, auth behavior, data semantics, and backwards-compatible environment variables.\n")
	b.WriteString("- Collect a baseline before changing implementation: container image size, startup time, idle RSS, peak RSS, CPU under representative load, p50/p95/p99 latency, throughput, error rate, pod restarts, OOMKilled events, and current Kubernetes requests/limits.\n")
	b.WriteString("- Profile the current implementation. Capture CPU and memory profiles, allocation hotspots, dependency latency, serialization overhead, database/query behavior, queue depth, and any runtime GC or event-loop/thread-pool pressure.\n")
	b.WriteString("- Document every assumption that cannot be verified locally and add a follow-up task for production or staging evidence.\n\n")

	b.WriteString("## Architecture Direction\n\n")
	b.WriteString("- First evaluate non-rewrite options: request tuning, lazy loading, dependency reduction, concurrency limits, caching with clear invalidation, worker separation, scale-to-zero, and moving only the hot path to a smaller service.\n")
	b.WriteString("- If a rewrite is justified, use an evolutionary migration. Keep the existing service as the rollback path and introduce the new Go service behind a feature flag, route split, queue consumer split, or shadow-read/shadow-write pattern where applicable.\n")
	b.WriteString("- Keep service boundaries boring and explicit. The new implementation should own the same contract unless the PR includes a reviewed API migration plan.\n")
	b.WriteString("- Apply AWS Well-Architected and Kubernetes production concerns: operational ownership, least privilege, secret handling, reliability during deploys, performance efficiency, cost controls, and sustainability through lower steady-state compute.\n")
	b.WriteString("- Do not add a new database, cache, queue, cloud service, or protocol unless the architecture section of the PR explains why existing components cannot satisfy the workload.\n\n")

	b.WriteString("## Implementation Requirements\n\n")
	b.WriteString("- Prefer Go for the first implementation unless repository evidence shows Rust is the better fit for an existing ecosystem or a CPU-bound native library path.\n")
	b.WriteString("- Keep memory use explicit: bounded buffers, request body limits, streaming where useful, connection pool limits, timeouts, cancellation propagation, and no unbounded goroutine or channel growth.\n")
	b.WriteString("- Preserve observability: structured logs, request IDs/correlation IDs, metrics for latency/error/saturation, health/readiness endpoints, dependency timing, and clear startup/shutdown logs.\n")
	b.WriteString("- Preserve security controls: authentication, authorization, input validation, output encoding, CORS/security headers if this service owns HTTP responses, secret redaction, dependency scanning, and no secret values in logs/tests/fixtures.\n")
	b.WriteString("- Preserve reliability controls: graceful shutdown, readiness that fails until dependencies are usable, liveness only for deadlock/crash detection, retry limits, backoff, idempotency for mutating operations, and explicit timeout budgets.\n")
	b.WriteString("- Keep deployment compatible with the current CI/CD path. Update Dockerfile, build workflow, Kubernetes manifest, api.yml, Helm values, or Kustomize overlays only where the service owner already maintains them.\n")
	b.WriteString("- Do not lower Kubernetes requests as part of the first rewrite PR unless the PR includes before/after load data. Resource reductions should follow validation, not precede it.\n\n")

	b.WriteString("## Performance Acceptance Criteria\n\n")
	b.WriteString("- The PR must include a baseline table and an after table using the same test method, data volume, concurrency, container limits, and environment.\n")
	b.WriteString("- Memory target: reduce steady-state and representative-load memory enough to create real bin-packing value. If the recommendation came from high observed memory, the new service must also prove it does not under-request memory.\n")
	b.WriteString("- Latency target: p95 and p99 latency must stay within current SLOs or improve. Do not trade lower memory for materially worse tail latency.\n")
	b.WriteString("- Throughput target: match or exceed current sustainable throughput at the same or lower CPU request, unless the product owner explicitly accepts lower throughput.\n")
	b.WriteString("- Startup and rollout target: startup time, readiness time, graceful shutdown, and rollout behavior must be measured and documented.\n")
	b.WriteString("- Cost target: explain how the measured resource reduction changes node bin-packing, HPA behavior, or scale-to-zero potential. Do not claim node savings without scheduler/request evidence.\n\n")

	b.WriteString("## Deep QA And Validation Plan\n\n")
	b.WriteString("- Unit tests: cover parsing, validation, business rules, error handling, retries/timeouts, config loading, and boundary cases.\n")
	b.WriteString("- Contract tests: compare old and new behavior for every public endpoint, queue message, webhook, CLI command, or background job contract. Include success, validation failure, auth failure, dependency failure, and empty-state cases.\n")
	b.WriteString("- Integration tests: run against the same backing stores or realistic local substitutes. Verify migrations, schema compatibility, transactional behavior, and idempotency.\n")
	b.WriteString("- End-to-end tests: exercise user-critical flows through the service boundary. Capture logs and evidence for successful and failed paths.\n")
	b.WriteString("- Load tests: define traffic shape, ramp, duration, concurrency, test data, stop conditions, monitoring, and expected p50/p95/p99 latency, throughput, errors, CPU, memory, GC, and dependency saturation.\n")
	b.WriteString("- Security tests: safe input-validation probes, auth/authorization checks, dependency audit, secret scan, container image scan, CI permission review, and verification that logs do not expose credentials or user-sensitive data.\n")
	b.WriteString("- Kubernetes tests: deploy to staging, verify readiness/liveness, resource usage, HPA math if present, PDB behavior, rolling update, rollback, pod restarts, OOMKilled events, CPU throttling, and node placement.\n")
	b.WriteString("- Canary: start with shadow traffic or a small routed percentage. Monitor latency, errors, saturation, memory, CPU, restarts, and business metrics for at least one peak period before full rollout.\n")
	b.WriteString("- Rollback: keep the old service deployable, document the exact rollback command or PR revert path, and verify rollback in staging before production rollout.\n\n")

	b.WriteString("## Pull Request Requirements\n\n")
	b.WriteString("- Include an architecture summary with alternatives considered and why the chosen approach wins.\n")
	b.WriteString("- Include the baseline and after measurements, method, sample size, environment, and confidence level.\n")
	b.WriteString("- Include a risk register covering correctness, reliability, security, performance, cost, operations, and rollback.\n")
	b.WriteString("- Include release steps, feature flags or traffic controls, validation dashboards/queries, alert expectations, and rollback steps.\n")
	b.WriteString("- Link this instructions file and the originating Cluster Optimizer finding in the PR body.\n\n")

	b.WriteString("## Context JSON\n\n")
	b.WriteString("```json\n")
	b.WriteString(prettyJSON(ctx))
	b.WriteString("\n```\n")
	return b.String()
}

func writeKV(b *strings.Builder, key, value string) {
	if strings.TrimSpace(value) == "" {
		value = "unknown"
	}
	fmt.Fprintf(b, "- %s: %s\n", key, value)
}

func (ctx rewriteContext) value(key string) string {
	return strings.TrimSpace(ctx[key])
}

func prettyJSON(ctx rewriteContext) string {
	keys := make([]string, 0, len(ctx))
	for key := range ctx {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("{")
	for i, key := range keys {
		if i > 0 {
			b.WriteString(",")
		}
		keyJSON, _ := json.Marshal(key)
		valueJSON, _ := json.Marshal(ctx[key])
		b.WriteString("\n  ")
		b.Write(keyJSON)
		b.WriteString(": ")
		b.Write(valueJSON)
	}
	if len(keys) > 0 {
		b.WriteString("\n")
	}
	b.WriteString("}")
	return b.String()
}
